# dont forget to add to  to /etc/hosts the following entry:
# 127.0.0.1 localhost

services:
    frontend:
      build:
        context: ./frontend
        dockerfile: ../docker/frontend/Dockerfile
    nginx:
      build:
        context: ./docker/nginx
      ports:
        - "8080:80"
        - "8443:443"
    postgres:
      image: postgres
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
        - postgres_data:/var/lib/postgresql/
      ports:
        - "${POSTGRES_PORT}:5432"

volumes:
  postgres_data: